### PR TITLE
Create Jersey 2.22 version

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by stefanseifert** [comment]
thanks! it's merged, snapshot is deployed.
please cross-check - give a ping if you need a release.

p.s. why not directly update to the latest jersey version? 2.25.1

**Comment by justinedelson** [comment]
Q: do you have a recommended deployment for the dependencies?

bq. p.s. why not directly update to the latest jersey version? 2.25.1

Because I'm working with a customer who needs 2.22 :)

**Comment by justinedelson** [comment]
oh, and thanks for applying so quickly :)

**Comment by stefanseifert** [comment]
>  Q: do you have a recommended deployment for the dependencies?

have a look at https://github.com/wcm-io-caravan/caravan-jaxrs/tree/develop/integration-test/launchpad-test

the most important deps should be
  javax.annotation/javax.annotation-api/1.2
  javax.validation/validation-api/1.1.0.Final
  javax.ws.rs/javax.ws.rs-api/2.0.1
  io.wcm.osgi.wrapper/io.wcm.osgi.wrapper.hibernate-validator/5.1.3-0000

**Pull request merged**
